site_name: Ansible
theme:
  name: material
  features:
    - navigation.tabs
    - toc.integrate
    - navigation.expand
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Poppins
    code: Cascadia Code
plugins:
    - search
nav:
  - Home: index.md
  - Basic:
    - YAML: Basic/yaml.md
    - Introduction: Basic/introduction.md
markdown_extensions:
  - abbr
  - pymdownx.mark
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - attr_list
  - def_list
  - pymdownx.smartsymbols
  - pymdownx.critic
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
